# Generated by Django 4.2.2 on 2023-06-09 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('username', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('faculty', models.CharField(default=' ', max_length=50)),
                ('semester', models.CharField(default=' ', max_length=50)),
                ('phone', models.CharField(default=' ', max_length=50)),
                ('email', models.CharField(default=' ', max_length=50)),
            ],
        ),
    ]
