# Generated by Django 4.2.2 on 2023-06-12 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='Form',
        ),
    ]
